db {
  host = "localhost"
  host = ${?DB_HOST}
  port = 5432
  port = ${?DB_PORT}
  name = "cfar_engine"
  name = ${?DB_NAME}
  user = "cfar"
  user = ${?DB_USER}
  password = "cfar_local"
  password = ${?DB_PASSWORD}
  poolSize = 10
  poolSize = ${?DB_POOL_SIZE}
}

app {
  port = 8080
  port = ${?APP_PORT}
  env = "development"
  env = ${?ENV}
  defaultCancellationWindowH = 24
  defaultCancellationWindowH = ${?DEFAULT_CANCELLATION_WINDOW_H}
  defaultCancellationRate = 0.095
  defaultCancellationRate = ${?DEFAULT_CANCELLATION_RATE}
  refundSimulationDelayS = 3
  refundSimulationDelayS = ${?REFUND_SIMULATION_DELAY_S}
}
